version: '3.7'

services:
  kalila-frontend:
    restart: unless-stopped
    container_name: kalila-frontend
    image: docker.kozae.de/kalila-frontend:dev
    volumes:
      - /root/Kalila/volumes/assets:/images
      - /root/Kalila/next/frontend:/frontend
      - /frontend/node_modules
    env_file:
      - .env
    ports:
      - '6000:6000'

networks:
  default:
    external: true
    name: kalila_kalilanet
#  docker logs -f kalila-frontend
