version: '3.7'

services:
  kalila-frontend:
    restart: unless-stopped
    container_name: kalila-frontend
    image: docker.kozae.de/kalila-frontend:latest
    env_file:
      - prod.env
    ports:
      - '6000:6000'
    volumes:
      - /root/Kalila/volumes/assets:/images
    network_mode: host

