import { ActivitySchema } from '@frontend/util';

export const bookUnitSchema: ActivitySchema = {
  Fields: [
    {
      DocumentName: 'BookUnit',
      FieldCategory: '',
      FieldName: 'chapter',
      FieldDisplay: 'Chapter',
      FieldNamePascalCase: 'Chapter',
      Readonly: false,
      Hidden: false,
      Unique: false,
      KeyField: true,
      TopField: false,
      Searchable: true,
      EditableInBulk: false,
      KalilaValueType: 9,
      ValueProperties: [],
      ConnectsToEntity: '',
      ConnectsToField: '',
      InputMode: 3,
      CategoricalAttributeType: 'Chapter',
    },
    {
      DocumentName: 'BookUnit',
      FieldCategory: '',
      FieldName: 'order in chapter',
      FieldDisplay: 'Order in Chapter',
      FieldNamePascalCase: 'OrderInChapter',
      Readonly: false,
      Hidden: false,
      Unique: false,
      KeyField: true,
      TopField: false,
      Searchable: true,
      EditableInBulk: false,
      KalilaValueType: 2,
      ValueProperties: [],
      ConnectsToEntity: '',
      ConnectsToField: '',
      InputMode: 0,
    },
    {
      DocumentName: 'BookUnit',
      FieldCategory: '',
      FieldName: 'title',
      FieldDisplay: 'Title',
      FieldNamePascalCase: 'Title',
      Readonly: false,
      Hidden: false,
      Unique: true,
      KeyField: true,
      TopField: true,
      Searchable: true,
      EditableInBulk: false,
      KalilaValueType: 0,
      ValueProperties: [],
      ConnectsToEntity: '',
      ConnectsToField: '',
      InputMode: 0,
    },
    {
      DocumentName: 'BookUnit',
      FieldCategory: '',
      FieldName: 'additional commentary',
      FieldDisplay: 'Additional Commentary',
      FieldNamePascalCase: 'AdditionalCommentary',
      Readonly: false,
      Hidden: false,
      Unique: false,
      KeyField: false,
      TopField: false,
      Searchable: true,
      EditableInBulk: false,
      KalilaValueType: 0,
      ValueProperties: [],
      ConnectsToEntity: '',
      ConnectsToField: '',
      InputMode: 9,
    },
    {
      DocumentName: 'BookUnit',
      FieldName: 'editor',
      FieldDisplay: 'Editor',
      FieldNamePascalCase: 'Editor',
      Readonly: true,
      Hidden: true,
      Unique: true,
      KeyField: false,
      TopField: false,
      Searchable: true,
      EditableInBulk: false,
      KalilaValueType: 0,
      InputMode: 15,
    },
    {
      DocumentName: 'BookUnit',
      FieldName: 'edition progress',
      FieldDisplay: 'Edition Progress',
      FieldNamePascalCase: 'EditionProgress',
      Readonly: true,
      Hidden: true,
      Unique: true,
      KeyField: false,
      TopField: false,
      Searchable: true,
      EditableInBulk: false,
      KalilaValueType: 0,
      InputMode: 15,
    },
    {
      DocumentName: 'BookUnit',
      FieldName: 'created at',
      FieldDisplay: 'Created At',
      FieldNamePascalCase: 'CreatedAt',
      Readonly: true,
      Hidden: true,
      Unique: true,
      KeyField: false,
      TopField: false,
      Searchable: false,
      EditableInBulk: false,
      KalilaValueType: 13,
      InputMode: 15,
    },
    {
      DocumentName: 'BookUnit',
      FieldName: 'version',
      FieldDisplay: 'Version',
      FieldNamePascalCase: 'Version',
      Readonly: true,
      Hidden: true,
      Unique: true,
      KeyField: false,
      TopField: false,
      Searchable: false,
      EditableInBulk: false,
      KalilaValueType: 13,
      InputMode: 15,
    },
  ],
  CategoricalAttributes: {
    Chapter: [
      'Ag',
      'As',
      'At',
      'Aw',
      'Bu',
      'Df',
      'Im',
      'Kb',
      'Kd',
      'Km',
      'Ks',
      'Kw',
      'Lh',
      'Lj',
      'Lo',
      'Lv',
      'Mc',
      'Oc',
      'Rd',
      'Sv',
      'Tg',
    ],
  },
};
