/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function editionstore_build_row(a: number, b: number): number;
export function editionstore_get_row_index(a: number, b: number, c: number, d: number): void;
export function editionstore_delete_row(a: number, b: number): number;
export function editionstore_insert_row(a: number, b: number): number;
export function editionstore_replace_rows(a: number, b: number): number;
export function editionrowtitle_get_display(a: number, b: number): void;
export function editionrowtitle_get_row_has_images(a: number): number;
export function editionrowtitle_get_order(a: number, b: number): void;
export function editionrowtitle_get_is_divider(a: number): number;
export function editionrowtitle_update_row(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbg_editioncelldata_free(a: number): void;
export function __wbg_editionrowtitle_free(a: number): void;
export function __wbg_editionstore_free(a: number): void;
export function editionstore_load(a: number, b: number): void;
export function editionstore_get_edition_id(a: number, b: number): void;
export function editionstore_get_name(a: number, b: number): void;
export function editionstore_get_no_manuscripts(a: number): number;
export function editionstore_get_ms_siglum(a: number, b: number, c: number): void;
export function editionstore_get_ms_id(a: number, b: number, c: number): void;
export function editionstore_get_ms_unit_presence_array(a: number, b: number, c: number): void;
export function editionstore_get_dividers(a: number, b: number): void;
export function editionstore_get_ms_image_presence_array(a: number, b: number, c: number): void;
export function editionstore_get_ms_sigla(a: number, b: number): void;
export function editionstore_get_no_rows(a: number): number;
export function editionstore_unit_is_in_edition(a: number, b: number, c: number): number;
export function editionstore_unit_is_in_range(a: number, b: number): number;
export function editionstore_get_manuscript_idx(a: number, b: number, c: number, d: number): void;
export function editionstore_is_page_in_edition(a: number, b: number, c: number): number;
export function editionstore_is_unit_lacuna(a: number, b: number, c: number): number;
export function editionstore_get_url(a: number, b: number, c: number, d: number): void;
export function editionstore_get_line_region(a: number, b: number, c: number, d: number): void;
export function editionstore_get_image_region(a: number, b: number, c: number, d: number): void;
export function editionstore_get_image_legend_region(a: number, b: number, c: number, d: number): void;
export function editionstore_get_image_legend_page_number(a: number, b: number, c: number): number;
export function editionstore_get_image_legend_token_count(a: number, b: number, c: number, d: number): void;
export function editionstore_get_image_legend_token(a: number, b: number, c: number, d: number, e: number): void;
export function editionstore_get_unit_image_page_number(a: number, b: number, c: number): number;
export function editionstore_get_unit_image_region(a: number, b: number, c: number, d: number): void;
export function editionstore_get_unit_image_legend_token_count(a: number, b: number, c: number, d: number): void;
export function editionstore_get_unit_image_legend_token(a: number, b: number, c: number, d: number, e: number): void;
export function editionstore_find_unit_by_order(a: number, b: number, c: number): void;
export function editionstore_find_unit_by_title(a: number, b: number, c: number, d: number): void;
export function editionstore_get_page_breaks(a: number, b: number): void;
export function editionstore_get_symbols(a: number, b: number): void;
export function editionstore_get_located_images(a: number, b: number): void;
export function editionstore_find_words(a: number, b: number, c: number, d: number): void;
export function editionstore_get_id(a: number, b: number): void;
export function editionstore_build_cell(a: number, b: number, c: number): number;
export function editionstore_update_ms_lacunae(a: number, b: number, c: number, d: number): number;
export function editionstore_update_cells(a: number, b: number, c: number): number;
export function editioncelldata_get_located_image_location(a: number, b: number): void;
export function editioncelldata_get_unit_idx(a: number, b: number): void;
export function editioncelldata_get_manuscript_idx(a: number): number;
export function editioncelldata_get_manuscript_siglum(a: number, b: number): void;
export function editioncelldata_get_unit_order(a: number): number;
export function editioncelldata_get_page(a: number, b: number): number;
export function editioncelldata_get_line_number(a: number, b: number): number;
export function editioncelldata_get_lines(a: number, b: number): void;
export function editioncelldata_get_tokens(a: number, b: number, c: number): void;
export function editioncelldata_get_tokens_indexes(a: number, b: number, c: number): void;
export function editioncelldata_get_page_range(a: number, b: number): void;
export function editioncelldata_is_first_token(a: number, b: number): number;
export function editioncelldata_get_unit(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
