/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_editioncelldata_free(a: number): void;
export function editioncelldata_get_key(a: number, b: number): void;
export function editioncelldata_get_token_count(a: number): number;
export function editioncelldata_get_unit_idx(a: number): number;
export function editioncelldata_get_manuscript_idx(a: number): number;
export function __wbg_imagestore_free(a: number): void;
export function imagestore_new(): number;
export function __wbg_manuscript_free(a: number): void;
export function __wbg_unit_free(a: number): void;
export function __wbg_facsimile_free(a: number): void;
export function __wbg_line_free(a: number): void;
export function __wbg_region_free(a: number): void;
export function __wbg_point_free(a: number): void;
export function __wbg_editionstore_free(a: number): void;
export function editionstore_load(a: number, b: number): void;
export function editionstore_get_name(a: number, b: number): void;
export function editionstore_get_id(a: number, b: number): void;
export function editionstore_get_no_manuscripts(a: number): number;
export function editionstore_get_ms_siglum(a: number, b: number, c: number): void;
export function editionstore_get_no_book_units(a: number): number;
export function editionstore_get_book_unit_display_title(a: number, b: number, c: number): void;
export function editionstore_get_book_unit_id(a: number, b: number, c: number): void;
export function editionstore_get_cell(a: number, b: number, c: number, d: number): number;
export function editionstore_get_token(a: number, b: number, c: number, d: number, e: number): void;
export function editionstore_store_image_data(a: number, b: number, c: number, d: number): void;
export function __wbg_bookunit_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
