import { IDataEntrySchema } from '@frontend/util';

export const CategoricalAttributes: Record<
  'Tags' | 'PresentPageNumbering' | 'EditionProgress',
  string[]
> = {
  EditionProgress: ['not started', 'in work', 'needs revision', 'finished'],
  PresentPageNumbering: ['by folio', 'by page', 'electronic'],
  Tags: [
    'Ag',
    'As',
    'At',
    'Aw',
    'Bu',
    'Df',
    'Di',
    'Im',
    'Kb',
    'Kd',
    'Km',
    'Ks',
    'Kw',
    'Lh',
    'Lj',
    'Lo',
    'Lv',
    'Mc',
    'Oc',
    'Rd',
    'Sv',
    'Tg',
    'colophon',
    'explicit',
    'incipit',
    'many hands',
    'no content',
    'other book',
    'paratext',
    'toc',
    'with blanks',
    'with illustrations',
    'with legends',
  ],
};

const Fields: IDataEntrySchema[] = [
  {
    DocumentName: 'Page',
    FieldName: 'edition progress',
    FieldDisplay: 'Edition Progress',
    FieldNamePascalCase: 'EditionProgress',
    Readonly: false,
    Hidden: false,
    Unique: false,
    KeyField: false,
    TopField: false,
    Searchable: true,
    EditableInBulk: false,
    KalilaValueType: 0,
    InputMode: 3,
    CategoricalAttributeType: 'EditionProgress',
  },
  {
    DocumentName: 'Page',
    FieldCategory: '',
    FieldName: 'present page numbering',
    FieldDisplay: 'Present Page Numbering',
    FieldNamePascalCase: 'PresentPageNumbering',
    Readonly: false,
    Hidden: false,
    Unique: false,
    KeyField: false,
    TopField: false,
    Searchable: true,
    EditableInBulk: true,
    KalilaValueType: 12,
    ValueProperties: [],
    ConnectsToEntity: '',
    ConnectsToField: '',
    InputMode: 5,
    CategoricalAttributeType: 'PresentPageNumbering',
  },
  {
    DocumentName: 'Page',
    FieldCategory: '',
    FieldName: 'pagination',
    FieldDisplay: 'Pagination',
    FieldNamePascalCase: 'Pagination',
    Readonly: false,
    Hidden: false,
    Unique: false,
    KeyField: false,
    TopField: false,
    Searchable: true,
    EditableInBulk: false,
    KalilaValueType: 1,
    ValueProperties: [],
    ConnectsToEntity: '',
    ConnectsToField: '',
    InputMode: 0,
  },
  {
    DocumentName: 'Page',
    FieldCategory: '',
    FieldName: 'foliation',
    FieldDisplay: 'Foliation',
    FieldNamePascalCase: 'Foliation',
    Readonly: false,
    Hidden: false,
    Unique: false,
    KeyField: false,
    TopField: false,
    Searchable: true,
    EditableInBulk: false,
    KalilaValueType: 0,
    ValueProperties: [],
    ConnectsToEntity: '',
    ConnectsToField: '',
    InputMode: 0,
  },
  {
    DocumentName: 'Page',
    FieldCategory: '',
    FieldName: 'tags',
    FieldDisplay: 'Tags',
    FieldNamePascalCase: 'Tags',
    Readonly: false,
    Hidden: false,
    Unique: false,
    KeyField: false,
    TopField: false,
    Searchable: true,
    EditableInBulk: true,
    KalilaValueType: 12,
    ValueProperties: [],
    ConnectsToEntity: '',
    ConnectsToField: '',
    InputMode: 5,
    CategoricalAttributeType: 'Tags',
  },
];

export const schema = {
  Fields,
  CategoricalAttributes,
};
